const SEARCH_CHAT = 'SEARCH_CHAT';
const GET_CHATS = 'GET_CHATS';
const ADD_CHAT = 'ADD_CHAT';
const DELETE_CHAT = 'DELETE_CHAT';
const GET_MESSAGES = 'GET_MESSAGES';
const SEND_MESSAGE = 'SEND_MESSAGE';

module.exports = {
  SEARCH_CHAT,
  GET_CHATS,
  ADD_CHAT,
  DELETE_CHAT,
  GET_MESSAGES,
  SEND_MESSAGE,
}
